### ISSUE TITLE
[Idea] Separate generate_world from scenes.py

### ISSUE THREAD

**Issue by trevortomesh** [XenonLab-Studio/TerraCraft#46]
It would be really great if we could separate the generate_world call from scenes.py! This would allow students to look at the source code and understand how proc. gen works -- but more importantly, it would allow them to write their own algorithms to generate terrain!

**Comment by trevortomesh** [comment]
I have this working in my fork; would it be of interest?

**Comment by benmoran56** [comment]
Yes, this is a good idea. I'll merge it in as it is, but I'll probably have to change it a bit when I do the refactors I had i mind.

**Comment by trevortomesh** [comment]
Great! Thanks!
